Repository percona/pg_stat_monitor, pull requests merged in 2022-06, with the labels that each got.

#256 PG-289: Remove ‘for’ loop initial declarations.
  pg_stat_monitor.c
Labels: Bug

#253 PG-362: pgsm_normalized_query needs to be 0 by default.
  guc.c
  regression/expected/application_name.out
  regression/expected/application_name_unique.out
  regression/expected/basic.out
  regression/expected/cmd_type.out
  regression/expected/error.out
  regression/expected/error_insert.out
  regression/expected/guc.out
  regression/expected/histogram.out
  regression/expected/histogram_1.out
  regression/expected/rows.out
  regression/expected/tags.out
  regression/expected/top_query.out
  t/expected/001_settings_default.out
  t/expected/002_settings_pgsm_track_planning.out
  t/expected/003_settings_pgms_extract_comments.out
  t/expected/004_settings_pgsm_track.out
  t/expected/005_settings_pgsm_enable_query_plan.out
  t/expected/006_settings_pgsm_overflow_target.out
  t/expected/007_settings_pgsm_query_shared_buffer.out
  t/expected/008_settings_pgsm_histogram_buckets.out
  t/expected/009_settings_pgsm_histogram_max.out
  t/expected/010_settings_pgsm_histogram_min.out
  t/expected/011_settings_pgsm_bucket_time.out
  t/expected/017_execution_stats.out
Labels: Enhancement

#257 PG-439: Remove warning of comparison of unsigned enum expression.
  pg_stat_monitor.c
Labels: warning

#260 PG-370 Release notes PGSM 1.0.0-rc1
  docs/RELEASE_NOTES.md
Labels: Documentation

#262 PG-300: Fix potential duplicate queryid issue.
  pg_stat_monitor.c
Labels: Bug

#267 PG-437: added the how we work section for OneFlow
  README.md
Labels: Documentation

#268 PG-453: Normalize query does not work with INSERT statements.        …
  pg_stat_monitor.c
Labels: Bug

#271 PG-449: Despite pgsm_extract_comments='no', comments are still visible.
  pg_stat_monitor.c
Labels: Bug

#269 PG-456: Running pgindent to make source PostgreSQL compatible.
  guc.c
  hash_query.c
  pg_stat_monitor.c
  pg_stat_monitor.h
  pgsm_errors.c
Labels: Enhancement

#276 Cherry-pick from REL_1_STABLE into main branch
  docs/USER_GUIDE.md
Labels: Documentation
